include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    unnecessary_brace_in_string_interps: ignore

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
